#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INIT_AGENT_PATH="${INIT_AGENT_PATH:-ckpt/PlaceCucumber-v1/sft/panda_widowx_widowx/vla_adapter_smolvla_efficientvla_sft/20260709-054512/best_agent.pt}" \
BACKBONE_LEARNING_RATE="${BACKBONE_LEARNING_RATE:-1e-6}" \
MAPLE_HEAD_LEARNING_RATE="${MAPLE_HEAD_LEARNING_RATE:-1e-6}" \
STATE_LEARNING_RATE="${STATE_LEARNING_RATE:-1e-6}" \
VALUE_HEAD_LEARNING_RATE="${VALUE_HEAD_LEARNING_RATE:-1e-4}" \
FUTURE_HEAD_LEARNING_RATE="${FUTURE_HEAD_LEARNING_RATE:-1e-6}" \
CLIP_EPS="${CLIP_EPS:-0.1}" \
TARGET_KL="${TARGET_KL:-0.02}" \
MAPLE_FUTURE_STATE_COEF="${MAPLE_FUTURE_STATE_COEF:-0.02}" \
MAPLE_LATENT_LAYERS="${MAPLE_LATENT_LAYERS:-2}" \
MAPLE_FUTURE_HORIZON="${MAPLE_FUTURE_HORIZON:-1}" \
MAPLE_RL_BC_COEF="${MAPLE_RL_BC_COEF:-0.0}" \
CRITIC_WARMUP_ROLLOUTS="${CRITIC_WARMUP_ROLLOUTS:-100}" \
FREEZE_VLA_BACKBONE="${FREEZE_VLA_BACKBONE:-1}" \
ALGO=maple "${SCRIPT_DIR}/run_baseline_pretrain.sh"
